-- Imdad AI - Supabase schema repair + clean demo reset
-- Run this entire file once in Supabase SQL Editor.

begin;

create table if not exists public.users (
  id uuid primary key,
  full_name text not null,
  email text not null unique,
  role text not null,
  employee_id text,
  department text,
  password_hash text,
  created_at timestamptz not null default now()
);

alter table public.users drop constraint if exists users_id_fkey;
alter table public.users add column if not exists full_name text;
alter table public.users add column if not exists email text;
alter table public.users add column if not exists role text;
alter table public.users add column if not exists employee_id text;
alter table public.users add column if not exists department text;
alter table public.users add column if not exists password_hash text;
alter table public.users add column if not exists created_at timestamptz not null default now();
alter table public.users drop constraint if exists users_role_check;
alter table public.users add constraint users_role_check check (role in ('User', 'Support Engineer', 'Admin'));
create unique index if not exists users_email_unique_idx on public.users (email);

create table if not exists public.knowledge_base (
  id int generated by default as identity primary key,
  issue_name text not null unique,
  keywords text[] not null default '{}',
  solution text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id int generated by default as identity primary key,
  ticket_id text not null unique,
  user_id uuid references public.users(id) on delete set null,
  user_name text not null,
  user_email text not null,
  issue_title text,
  issue_description text not null,
  ai_suggestion text not null,
  priority text not null,
  assigned_team text not null,
  assigned_engineer uuid references public.users(id) on delete set null,
  assigned_engineer_name text not null default 'Unassigned',
  status text not null,
  resolution text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tickets add column if not exists issue_title text;
alter table public.tickets add column if not exists assigned_engineer_name text not null default 'Unassigned';
alter table public.tickets add column if not exists resolution text;
alter table public.tickets add column if not exists updated_at timestamptz not null default now();
update public.tickets set issue_title = issue_description where issue_title is null;
update public.tickets set status = 'In Progress' where status = 'Assigned';
alter table public.tickets drop constraint if exists tickets_status_check;
alter table public.tickets add constraint tickets_status_check check (status in ('Open', 'In Progress', 'Resolved', 'Closed'));
alter table public.tickets drop constraint if exists tickets_priority_check;
alter table public.tickets add constraint tickets_priority_check check (priority in ('Low', 'Medium', 'High', 'Critical'));

create table if not exists public.chat_history (
  id int generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  user_name text not null,
  user_email text not null,
  issue text not null,
  ai_response text not null,
  source text not null,
  result text not null,
  ticket_id text references public.tickets(ticket_id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.chat_history drop constraint if exists chat_history_source_check;
alter table public.chat_history add constraint chat_history_source_check check (source in ('Knowledge Base', 'AI Assistant'));

create table if not exists public.ticket_resolution_history (
  id int generated by default as identity primary key,
  ticket_id text not null references public.tickets(ticket_id) on delete cascade,
  engineer_name text not null,
  engineer_email text not null,
  previous_status text,
  new_status text not null,
  remarks text,
  resolution_notes text,
  created_at timestamptz not null default now()
);

alter table public.ticket_resolution_history drop constraint if exists ticket_resolution_history_new_status_check;
alter table public.ticket_resolution_history add constraint ticket_resolution_history_new_status_check check (new_status in ('Open', 'In Progress', 'Resolved', 'Closed'));

create index if not exists tickets_user_email_idx on public.tickets (user_email);
create index if not exists tickets_status_idx on public.tickets (status);
create index if not exists tickets_priority_idx on public.tickets (priority);
create index if not exists tickets_updated_at_idx on public.tickets (updated_at);
create index if not exists chat_history_user_email_idx on public.chat_history (user_email);
create index if not exists ticket_resolution_history_ticket_id_idx on public.ticket_resolution_history (ticket_id);

alter table public.users enable row level security;
alter table public.knowledge_base enable row level security;
alter table public.tickets enable row level security;
alter table public.chat_history enable row level security;
alter table public.ticket_resolution_history enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Allow anon manage users for prototype') then
    create policy "Allow anon manage users for prototype" on public.users for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'knowledge_base' and policyname = 'Allow anon manage knowledge base for prototype') then
    create policy "Allow anon manage knowledge base for prototype" on public.knowledge_base for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'tickets' and policyname = 'Allow anon manage tickets for prototype') then
    create policy "Allow anon manage tickets for prototype" on public.tickets for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'chat_history' and policyname = 'Allow anon manage chat history for prototype') then
    create policy "Allow anon manage chat history for prototype" on public.chat_history for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ticket_resolution_history' and policyname = 'Allow anon manage ticket resolution history for prototype') then
    create policy "Allow anon manage ticket resolution history for prototype" on public.ticket_resolution_history for all to anon using (true) with check (true);
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'users') then
      alter publication supabase_realtime add table public.users;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tickets') then
      alter publication supabase_realtime add table public.tickets;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'knowledge_base') then
      alter publication supabase_realtime add table public.knowledge_base;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_history') then
      alter publication supabase_realtime add table public.chat_history;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'ticket_resolution_history') then
      alter publication supabase_realtime add table public.ticket_resolution_history;
    end if;
  end if;
end $$;

truncate table public.ticket_resolution_history restart identity cascade;
truncate table public.chat_history restart identity cascade;
truncate table public.tickets restart identity cascade;
truncate table public.knowledge_base restart identity cascade;
truncate table public.users restart identity cascade;

insert into public.users (id, full_name, email, role, employee_id, department, password_hash, created_at)
values
  ('11111111-1111-4111-8111-111111111111', 'Aarav Mehta', 'aarav.mehta@acme.local', 'User', 'EMP-1001', 'Information Technology', '03425700e3df805de1330c7eabe08dec874e3f181ab466e67b3c5bdf5bda6cff', now()),
  ('22222222-2222-4222-8222-222222222222', 'Neha Kapoor', 'neha.kapoor@acme.local', 'User', 'EMP-1002', 'Finance', 'ac7ae991511745e83b9106ec51805c5cb430e5e3f7027574d79e1c3532c32f64', now()),
  ('33333333-3333-4333-8333-333333333333', 'Priya Nair', 'priya.nair@support.local', 'Support Engineer', 'ENG-2001', 'IT Support Team', 'b43badcc58f3065cb03c62360b28710d6e345a37a8987e94b05227a310552f28', now()),
  ('44444444-4444-4444-8444-444444444444', 'Maya Rao', 'maya.rao@admin.local', 'Admin', 'ADM-3001', 'IT Operations', '95b358faa10644f768a38805d0f9194f9c1fb2bc780808260243339cfaee3caf', now());

insert into public.knowledge_base (issue_name, keywords, solution, created_at, updated_at)
values
  ('VPN connection issue', array['vpn','network','remote','connection','tunnel','timeout','mfa'], 'Confirm internet access, restart the VPN client, clear saved credentials, and reconnect using MFA. If the gateway still times out, attach the error code to a network ticket.', now(), now()),
  ('Wi-Fi not working', array['wifi','wi-fi','wireless','network','internet','ssid','router'], 'Forget and reconnect to the corporate Wi-Fi, confirm the correct SSID, restart the wireless adapter, and test another network. Escalate with device name and location if signal or DHCP fails.', now(), now()),
  ('Email not receiving', array['email','outlook','mail','receive','receiving','inbox','sync'], 'Check mailbox quota, junk rules, focused inbox, and service health. Restart Outlook or webmail, then remove and re-add the profile if incoming mail remains delayed.', now(), now()),
  ('Email blocked', array['email','blocked','quarantine','spam','delivery','bounce','sender'], 'Check quarantine, blocked sender rules, and mail flow notices. Ask the sender for the bounce message and release the email only after verifying it is safe.', now(), now()),
  ('Password reset', array['password','reset','forgot','locked','mfa','credential'], 'Use the self-service password portal, verify MFA, then wait two minutes before signing in again. Escalate if the account is locked after three attempts.', now(), now()),
  ('Login issue', array['login','signin','sign in','authentication','mfa','account','locked'], 'Confirm the username, password, MFA approval, and account status. Try a private browser window and capture the exact login error if access still fails.', now(), now()),
  ('Access denied', array['access','denied','permission','unauthorized','role'], 'Capture the application name and request the correct access group. Ask the user''s manager to approve the entitlement before assignment.', now(), now()),
  ('Slow system', array['slow','performance','laptop','system','hang'], 'Restart the device, close high-memory apps, check disk space, install pending updates, and run the endpoint health scan from Company Portal.', now(), now()),
  ('Printer issue', array['printer','print','paper','queue','spooler'], 'Confirm the printer is online, clear the local print queue, restart the print spooler, and reinstall the printer from the managed printer catalog.', now(), now()),
  ('Software installation issue', array['software','install','installation','application','license','setup'], 'Check whether the app is approved in the software catalog. If approved, install through Company Portal; otherwise submit a license and security review request.', now(), now()),
  ('Laptop screen flickering', array['laptop','screen','flickering','display','monitor','graphics'], 'Restart the laptop, update display drivers, test with an external monitor, and reduce refresh-rate changes. Escalate with device model and whether flicker appears before login.', now(), now()),
  ('Teams meeting issue', array['teams','meeting','audio','camera','microphone','call','conference'], 'Restart Teams, check microphone and camera permissions, switch audio devices, clear Teams cache, and join from the browser if the desktop client fails.', now(), now()),
  ('Portal down', array['portal','down','unavailable','website','page','error','service'], 'Check the service status page, try a different browser, clear cache, and confirm whether multiple users are affected. Escalate as an application incident if the portal remains unavailable.', now(), now()),
  ('Server down', array['server','down','outage','service','unavailable','production'], 'Validate monitoring alerts, check incident channels, confirm service health, and page the infrastructure on-call team with affected service, region, and start time.', now(), now()),
  ('Application not opening', array['application','app','not opening','crash','launch','startup','blank'], 'Restart the application, check for updates, clear local cache, and try launching as a different profile. Escalate with app version, screenshot, and event log details.', now(), now()),
  ('File or folder missing', array['file','folder','missing','deleted','onedrive','sharepoint','restore'], 'Check recycle bin, OneDrive or SharePoint version history, sync status, and recent moves. Escalate with file path, owner, and last known access time if recovery is needed.', now(), now());

insert into public.tickets (
  ticket_id,
  user_id,
  user_name,
  user_email,
  issue_title,
  issue_description,
  ai_suggestion,
  priority,
  assigned_team,
  assigned_engineer,
  assigned_engineer_name,
  status,
  resolution,
  created_at,
  updated_at
)
values
  ('TKT-0001', '22222222-2222-4222-8222-222222222222', 'Neha Kapoor', 'neha.kapoor@acme.local', 'Access denied to finance dashboard', 'Access denied when opening the finance reporting dashboard.', 'Likely missing finance-reporting entitlement. Verify group membership and manager approval.', 'High', 'Access Management Team', '33333333-3333-4333-8333-333333333333', 'Priya Nair', 'In Progress', 'Approval received. Waiting for group sync.', now() - interval '2 hours', now() - interval '1 hour'),
  ('TKT-0002', '11111111-1111-4111-8111-111111111111', 'Aarav Mehta', 'aarav.mehta@acme.local', 'Laptop slow after update', 'Laptop is slow after today''s update and Teams calls freeze.', 'Restart, check CPU and memory pressure, validate disk space, and run endpoint health scan.', 'Medium', 'Hardware Team', null, 'Unassigned', 'Open', '', now() - interval '90 minutes', now() - interval '90 minutes');

insert into public.chat_history (user_id, user_name, user_email, issue, ai_response, source, result, ticket_id, created_at)
values
  ('11111111-1111-4111-8111-111111111111', 'Aarav Mehta', 'aarav.mehta@acme.local', 'How do I reset my password?', 'Use the self-service password portal, verify MFA, then wait two minutes before signing in again. Escalate if the account is locked after three attempts.', 'Knowledge Base', 'Resolved without ticket', null, now() - interval '3 hours'),
  ('22222222-2222-4222-8222-222222222222', 'Neha Kapoor', 'neha.kapoor@acme.local', 'Access denied when opening the finance reporting dashboard.', 'Capture the application name and request the correct access group. Ask the user''s manager to approve the entitlement before assignment.', 'Knowledge Base', 'Ticket created', 'TKT-0001', now() - interval '2 hours');

insert into public.ticket_resolution_history (ticket_id, engineer_name, engineer_email, previous_status, new_status, remarks, resolution_notes, created_at)
values
  ('TKT-0001', 'Priya Nair', 'priya.nair@support.local', 'Open', 'In Progress', 'Assigned access request to support engineer after entitlement check.', 'Approval received. Waiting for group sync.', now() - interval '1 hour');

commit;
